### ISSUE TITLE
Фиксы будущих проблемы в Мете после апстримов

### ISSUE THREAD

**Issue by Schrodinger71** [xtray85/space_station#578]
## Скриншоты

![image](https://github.com/xtray85/space_station/assets/132720404/8c8df48d-30ab-4bde-9ce8-e4b8e0f7cc91)

**Comment by Darki255** [comment]
> ## Описание
> ## _**Все файлы на данном скрине, нужно перенести в Textures/ADT/ папки**_
> ## _**Также поправить YAMl файлы привязанные к этим спрайтам**_
> ## _**Всё что в папке toys.rsi**_
> ## Скриншоты
> ![image](https://private-user-images.githubusercontent.com/132720404/320977568-8c8df48d-30ab-4bde-9ce8-e4b8e0f7cc91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjUwNDYsIm5iZiI6MTcxNzI2NDc0NiwicGF0aCI6Ii8xMzI3MjA0MDQvMzIwOTc3NTY4LThjOGRmNDhkLTMwYWItNGJkZS05Y2U4LWU0YjhlMGY3Y2M5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNzU5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2E3Nzg2OTQzMTA1MGU5ZjhmZWEyY2ZlNDdlMjA2YjgwOTA2OTkwODVkYzRiNDgyNTRlYjQ3YWZjYjViOGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7lNCRSTYUGcX7xLobPjrU-IZM7xFH_10SI62aXMM3wE)

Сделано #741

**Comment by Schrodinger71** [comment]
Хорош
