### ISSUE TITLE
Фиксы меты

### ISSUE THREAD

**Issue by Schrodinger71** [xtray85/space_station#579]
### Скриншоты

![image](https://github.com/xtray85/space_station/assets/132720404/e478a909-ee1d-4d07-b371-50dcc9ed8225)

**Comment by Darki255** [comment]
> ### Описание
> ## Перенести эту png в ADT ПАПКУ
> ### Скриншоты
> ![image](https://private-user-images.githubusercontent.com/132720404/320980559-e478a909-ee1d-4d07-b371-50dcc9ed8225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjQ5NjksIm5iZiI6MTcxNzI2NDY2OSwicGF0aCI6Ii8xMzI3MjA0MDQvMzIwOTgwNTU5LWU0NzhhOTA5LWVlMWQtNGQwNy1iMzcxLTUwZGNjOWVkODIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNzU3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzJhMTllZGU1NWFiZTdiYTJhMjc0NWM4NWEzNjAyOGEyZjkwY2M3MjVlMmM3ZmM2ZWNiNWI2MDNkYjlkMzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0GCaJAXe_u2xszd1MCr_Qinpo_qQbTIVarIoRqAHriw)

Сделано #741
